# Generated by Django 2.1.4 on 2019-01-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('is_default', models.BooleanField(default=False, verbose_name='Изображение по-умолчанию')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Сорт',
                'verbose_name_plural': 'Сорта',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('year', models.SmallIntegerField(verbose_name='Год выпуска')),
                ('added_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления')),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнеднего изменения')),
                ('seen', models.IntegerField(default=0, verbose_name='Просмотрено')),
                ('rating', models.DecimalField(decimal_places=2, default=5, max_digits=3, verbose_name='Рейтинг')),
                ('kind', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='label.Kind', verbose_name='Сорт')),
            ],
            options={
                'verbose_name': 'Этикетка',
                'verbose_name_plural': 'Этикетки',
            },
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.AddField(
            model_name='label',
            name='manufacture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labels', to='label.Manufacture', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='image',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='label.Label', verbose_name='Этикетка'),
        ),
    ]
