# Generated by Django 2.1.4 on 2018-12-27 07:21

from datetime import datetime
from django.db import migrations, models


def forward_set_datetime(apps, schema_editor):
    Label = apps.get_model('label', 'Label')
    for label in Label.objects.all():
        label.added_dt = datetime.now()
        label.updated_dt = datetime.now()
        label.save()


def reverse_unset_datetime(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='kind',
            options={'verbose_name': 'Сорт', 'verbose_name_plural': 'Сорта'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Этикетка', 'verbose_name_plural': 'Этикетки'},
        ),
        migrations.AlterModelOptions(
            name='manufactory',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AddField(
            model_name='label',
            name='added_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата добавления'),
        ),
        migrations.AddField(
            model_name='label',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнеднего изменения'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.RunPython(
            forward_set_datetime, reverse_unset_datetime
        )
    ]
