# Generated by Django 2.1.4 on 2018-12-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0002_auto_20181227_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='seen',
            field=models.IntegerField(default=0, verbose_name='Просмотрено'),
        ),
    ]
