# Generated by Django 2.1.4 on 2018-12-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0003_label_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3, verbose_name='Рейтинг'),
        ),
    ]
